//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleProjectPackage.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleProjectPackage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string @__have_any_of_the_following_characters__________________________ {
            get {
                return ResourceManager.GetString("- have any of the following characters: / ? : &  \\ * \" < > | # %", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Reference ähnelt.
        /// </summary>
        internal static string AddReferenceDialogTitle {
            get {
                return ResourceManager.GetString("AddReferenceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to add file &apos;{0}&apos; to project as project is null. ähnelt.
        /// </summary>
        internal static string AddToNullProjectError {
            get {
                return ResourceManager.GetString("AddToNullProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced ähnelt.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy always ähnelt.
        /// </summary>
        internal static string Always {
            get {
                return ResourceManager.GetString("Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not load attribute &apos;{0}&apos; from project file &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string AttributeLoad {
            get {
                return ResourceManager.GetString("AttributeLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build Action ähnelt.
        /// </summary>
        internal static string BuildAction {
            get {
                return ResourceManager.GetString("BuildAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How the file relates to the build and deployment process ähnelt.
        /// </summary>
        internal static string BuildActionDescription {
            get {
                return ResourceManager.GetString("BuildActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build ähnelt.
        /// </summary>
        internal static string BuildCaption {
            get {
                return ResourceManager.GetString("BuildCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exception was thrown during BuildBegin event\n{0} ähnelt.
        /// </summary>
        internal static string BuildEventError {
            get {
                return ResourceManager.GetString("BuildEventError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbosity ähnelt.
        /// </summary>
        internal static string BuildVerbosity {
            get {
                return ResourceManager.GetString("BuildVerbosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specify how much information is included in the build output ähnelt.
        /// </summary>
        internal static string BuildVerbosityDescription {
            get {
                return ResourceManager.GetString("BuildVerbosityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The command you are attempting cannot be completed because the file &apos;{0}&apos; that must be modified cannot be changed. If the file is under source control, you may want to check it out; if the file is read-only on disk, you may want to change its attributes. ähnelt.
        /// </summary>
        internal static string CancelQueryEdit {
            get {
                return ResourceManager.GetString("CancelQueryEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A file with name &apos;{0}&apos; already exists and is open in an editor. Please give a unique name to the item you are adding, or delete the existing item first. ähnelt.
        /// </summary>
        internal static string CannotAddFileThatIsOpenInEditor {
            get {
                return ResourceManager.GetString("CannotAddFileThatIsOpenInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project &apos;{0}&apos; is targeting &apos;{1}&apos;; however, the target framework is not installed on the machine. ähnelt.
        /// </summary>
        internal static string CannotLoadUnknownTargetFrameworkProject {
            get {
                return ResourceManager.GetString("CannotLoadUnknownTargetFrameworkProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot save &apos;{0}&apos; as it is not open in the editor. ähnelt.
        /// </summary>
        internal static string CanNotSaveFileNotOpeneInEditor {
            get {
                return ResourceManager.GetString("CanNotSaveFileNotOpeneInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECMA-335 CLI compatible framework (location must be provided) ähnelt.
        /// </summary>
        internal static string cli1 {
            get {
                return ResourceManager.GetString("cli1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compile ähnelt.
        /// </summary>
        internal static string Compile {
            get {
                return ResourceManager.GetString("Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you change a file name extension, the file may become unusable. Are you sure you want to change it? ähnelt.
        /// </summary>
        internal static string ConfirmExtensionChange {
            get {
                return ResourceManager.GetString("ConfirmExtensionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content ähnelt.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy Local ähnelt.
        /// </summary>
        internal static string CopyToLocal {
            get {
                return ResourceManager.GetString("CopyToLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Indicates whether the reference will be copied to the output directory. ähnelt.
        /// </summary>
        internal static string CopyToLocalDescription {
            get {
                return ResourceManager.GetString("CopyToLocalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy to Output Directory ähnelt.
        /// </summary>
        internal static string CopyToOutputDirectory {
            get {
                return ResourceManager.GetString("CopyToOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Indicates whether the file will be copied to the output directory. ähnelt.
        /// </summary>
        internal static string CopyToOutputDirectoryDescription {
            get {
                return ResourceManager.GetString("CopyToOutputDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Tool ähnelt.
        /// </summary>
        internal static string CustomTool {
            get {
                return ResourceManager.GetString("CustomTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specifies the tool that transforms a file at design time and places the output of that transformation into another file. For example, a dataset (.xsd) file comes with a default custom tool. ähnelt.
        /// </summary>
        internal static string CustomToolDescription {
            get {
                return ResourceManager.GetString("CustomToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Tool Namespace ähnelt.
        /// </summary>
        internal static string CustomToolNamespace {
            get {
                return ResourceManager.GetString("CustomToolNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The namespace into which the output of the custom tool is placed. ähnelt.
        /// </summary>
        internal static string CustomToolNamespaceDescription {
            get {
                return ResourceManager.GetString("CustomToolNamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detailed ähnelt.
        /// </summary>
        internal static string Detailed {
            get {
                return ResourceManager.GetString("Detailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An &apos;Import&apos; of the file &apos;{1}&apos; was found in the project file &apos;{0}&apos;. This file is not registered as a safe file to import, and could contain targets and tasks that are harmful.  If this imported file is indeed considered safe, then it can be registered by writing to the registry key {2}. ähnelt.
        /// </summary>
        internal static string DetailsImport {
            get {
                return ResourceManager.GetString("DetailsImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One or more items named &apos;{1}&apos; were found in the project file &apos;{0}&apos;. These items normally should not be specified in the project file. They can change the way targets and tasks are executed during project load, and this could have harmful effects. ähnelt.
        /// </summary>
        internal static string DetailsItem {
            get {
                return ResourceManager.GetString("DetailsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An item referring to the file &apos;{1}&apos; was found in the project file &apos;{0}&apos;.  Since this file is located within a system directory, root directory, or network share, it could be harmful to write to this file. ähnelt.
        /// </summary>
        internal static string DetailsItemLocation {
            get {
                return ResourceManager.GetString("DetailsItemLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A property named &apos;{1}&apos; was found in the project file &apos;{0}&apos;.  This property normally should not be specified in the project file.  Its value can change the way targets and tasks are executed during project load, and this could have harmful effects. ähnelt.
        /// </summary>
        internal static string DetailsProperty {
            get {
                return ResourceManager.GetString("DetailsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A &apos;Target&apos; named &apos;{1}&apos; was found in the project file &apos;{0}&apos;.  The tasks within this target could contain arbitrary code and may get executed as soon as the project is loaded in the IDE. ähnelt.
        /// </summary>
        internal static string DetailsTarget {
            get {
                return ResourceManager.GetString("DetailsTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An &apos;Import&apos; of the file &apos;{1}&apos; was found in the user project file &apos;{0}&apos;.  All imports in user project files are considered unsafe. ähnelt.
        /// </summary>
        internal static string DetailsUserImport {
            get {
                return ResourceManager.GetString("DetailsUserImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A &apos;UsingTask&apos; tag which registers the &apos;{1}&apos; task was found in the project file &apos;{0}&apos;.  &apos;UsingTask&apos; tags in the project file take precedence over those in the imported .TARGETS files, and therefore could be used to execute arbitrary code during an otherwise unmodified build process. ähnelt.
        /// </summary>
        internal static string DetailsUsingTask {
            get {
                return ResourceManager.GetString("DetailsUsingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diagnostic ähnelt.
        /// </summary>
        internal static string Diagnostic {
            get {
                return ResourceManager.GetString("Diagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Directory already exists ähnelt.
        /// </summary>
        internal static string DirectoryExistError {
            get {
                return ResourceManager.GetString("DirectoryExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do not copy ähnelt.
        /// </summary>
        internal static string DoNotCopy {
            get {
                return ResourceManager.GetString("DoNotCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error opening specified view &apos;{0}&apos; using editor &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string EditorViewError {
            get {
                return ResourceManager.GetString("EditorViewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Embedded Resource ähnelt.
        /// </summary>
        internal static string EmbeddedResource {
            get {
                return ResourceManager.GetString("EmbeddedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Embed Interop Types ähnelt.
        /// </summary>
        internal static string EmbedInteropTypes {
            get {
                return ResourceManager.GetString("EmbedInteropTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Whether to include the COM interface definitions directly in the compiled assembly. ähnelt.
        /// </summary>
        internal static string EmbedInteropTypesDescription {
            get {
                return ResourceManager.GetString("EmbedInteropTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Files and folders cannot be: ähnelt.
        /// </summary>
        internal static string ErrorInvalidFileName {
            get {
                return ResourceManager.GetString("ErrorInvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name you provided is not a valid project name. ähnelt.
        /// </summary>
        internal static string ErrorInvalidProjectName {
            get {
                return ResourceManager.GetString("ErrorInvalidProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MSBuild path not found in registry. Please reinstall to fix the problem. ähnelt.
        /// </summary>
        internal static string ErrorMsBuildRegistration {
            get {
                return ResourceManager.GetString("ErrorMsBuildRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A reference to {0} could not be added. Please make sure that the file is accessible, and that it is a valid assembly or COM component. ähnelt.
        /// </summary>
        internal static string ErrorReferenceCouldNotBeAdded {
            get {
                return ResourceManager.GetString("ErrorReferenceCouldNotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Saving File ähnelt.
        /// </summary>
        internal static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Console Application ähnelt.
        /// </summary>
        internal static string Exe {
            get {
                return ResourceManager.GetString("Exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expecting object of type {0}. ähnelt.
        /// </summary>
        internal static string ExpectedObjectOfType {
            get {
                return ResourceManager.GetString("ExpectedObjectOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to retrieve MSBuild property {0} from the project file. ähnelt.
        /// </summary>
        internal static string FailedToRetrieveProperties {
            get {
                return ResourceManager.GetString("FailedToRetrieveProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A file with the same name &apos;{0}&apos; already exists. Do you want to overwrite it? ähnelt.
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A file with the same name &apos;{0}&apos; already exists. ähnelt.
        /// </summary>
        internal static string FileAlreadyExistsAndCannotBeRenamed {
            get {
                return ResourceManager.GetString("FileAlreadyExistsAndCannotBeRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destination File Exists ähnelt.
        /// </summary>
        internal static string FileAlreadyExistsCaption {
            get {
                return ResourceManager.GetString("FileAlreadyExistsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A file of this name is already part of the project. Do you want to overwrite it? ähnelt.
        /// </summary>
        internal static string FileAlreadyInProject {
            get {
                return ResourceManager.GetString("FileAlreadyInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destination File Exists ähnelt.
        /// </summary>
        internal static string FileAlreadyInProjectCaption {
            get {
                return ResourceManager.GetString("FileAlreadyInProjectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A file or folder with the name &apos;{0}&apos; already exists on disk at this location. Please choose another name. ähnelt.
        /// </summary>
        internal static string FileCannotBeRenamedToAnExistingFile {
            get {
                return ResourceManager.GetString("FileCannotBeRenamedToAnExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Copying File ähnelt.
        /// </summary>
        internal static string FileCopyError {
            get {
                return ResourceManager.GetString("FileCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Name ähnelt.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File and folder names cannot contain a leading period. ähnelt.
        /// </summary>
        internal static string FileNameCannotContainALeadingPeriod {
            get {
                return ResourceManager.GetString("FileNameCannotContainALeadingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name of the file or folder ähnelt.
        /// </summary>
        internal static string FileNameDescription {
            get {
                return ResourceManager.GetString("FileNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A file or folder with the name &apos;{0}&apos; already exists on disk at this location. Please choose another name. ähnelt.
        /// </summary>
        internal static string FileOrFolderAlreadyExists {
            get {
                return ResourceManager.GetString("FileOrFolderAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The item &apos;{0}&apos; cannot be found on disk, either because it has been renamed, deleted, or moved to a new location. ähnelt.
        /// </summary>
        internal static string FileOrFolderCannotBeFound {
            get {
                return ResourceManager.GetString("FileOrFolderCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Properties ähnelt.
        /// </summary>
        internal static string FileProperties {
            get {
                return ResourceManager.GetString("FileProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder Name ähnelt.
        /// </summary>
        internal static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of this folder ähnelt.
        /// </summary>
        internal static string FolderNameDescription {
            get {
                return ResourceManager.GetString("FolderNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder Properties ähnelt.
        /// </summary>
        internal static string FolderProperties {
            get {
                return ResourceManager.GetString("FolderProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Full Path ähnelt.
        /// </summary>
        internal static string FullPath {
            get {
                return ResourceManager.GetString("FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location of the file ähnelt.
        /// </summary>
        internal static string FullPathDescription {
            get {
                return ResourceManager.GetString("FullPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imagelis {
            get {
                object obj = ResourceManager.GetObject("imagelis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automation object invalid. ähnelt.
        /// </summary>
        internal static string InvalidAutomationObject {
            get {
                return ResourceManager.GetString("InvalidAutomationObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid logger type\nExpected: {0}\nReceived: {1} ähnelt.
        /// </summary>
        internal static string InvalidLoggerType {
            get {
                return ResourceManager.GetString("InvalidLoggerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die InvalidParameter ähnelt.
        /// </summary>
        internal static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The item &apos;{0}&apos; does not exist in the project directory. It may have been moved, renamed or deleted. ähnelt.
        /// </summary>
        internal static string ItemDoesNotExistInProjectDirectory {
            get {
                return ResourceManager.GetString("ItemDoesNotExistInProjectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Class Library ähnelt.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot save &apos;{0}&apos; outside the project directory. Linked items are not supported. ähnelt.
        /// </summary>
        internal static string LinkedItemsAreNotSupported {
            get {
                return ResourceManager.GetString("LinkedItemsAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimal ähnelt.
        /// </summary>
        internal static string Minimal {
            get {
                return ResourceManager.GetString("Minimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Misc ähnelt.
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The nested project has failed to reload. ähnelt.
        /// </summary>
        internal static string NestedProjectFailedToReload {
            get {
                return ResourceManager.GetString("NestedProjectFailedToReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normal ähnelt.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Primary Output ähnelt.
        /// </summary>
        internal static string OutputBuilt {
            get {
                return ResourceManager.GetString("OutputBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contains the DLL or EXE built by the project. ähnelt.
        /// </summary>
        internal static string OutputBuiltDescription {
            get {
                return ResourceManager.GetString("OutputBuiltDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content Files ähnelt.
        /// </summary>
        internal static string OutputContentFiles {
            get {
                return ResourceManager.GetString("OutputContentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contains all content files in the project. ähnelt.
        /// </summary>
        internal static string OutputContentFilesDescription {
            get {
                return ResourceManager.GetString("OutputContentFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Documentation Files ähnelt.
        /// </summary>
        internal static string OutputDocumentation {
            get {
                return ResourceManager.GetString("OutputDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contains the XML Documentation files for the project. ähnelt.
        /// </summary>
        internal static string OutputDocumentationDescription {
            get {
                return ResourceManager.GetString("OutputDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Localized Resources ähnelt.
        /// </summary>
        internal static string OutputLocalizedResourceDlls {
            get {
                return ResourceManager.GetString("OutputLocalizedResourceDlls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contains the satellite assemblies for each culture&apos;s resources. ähnelt.
        /// </summary>
        internal static string OutputLocalizedResourceDllsDescription {
            get {
                return ResourceManager.GetString("OutputLocalizedResourceDllsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output Path ähnelt.
        /// </summary>
        internal static string OutputPath {
            get {
                return ResourceManager.GetString("OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The path to the primary output ähnelt.
        /// </summary>
        internal static string OutputPathDescription {
            get {
                return ResourceManager.GetString("OutputPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source Files ähnelt.
        /// </summary>
        internal static string OutputSourceFiles {
            get {
                return ResourceManager.GetString("OutputSourceFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contains all source files in the project. ähnelt.
        /// </summary>
        internal static string OutputSourceFilesDescription {
            get {
                return ResourceManager.GetString("OutputSourceFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug Symbols ähnelt.
        /// </summary>
        internal static string OutputSymbols {
            get {
                return ResourceManager.GetString("OutputSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contains the debugging files for the project. ähnelt.
        /// </summary>
        internal static string OutputSymbolsDescription {
            get {
                return ResourceManager.GetString("OutputSymbolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XML Serialization Assemblies ähnelt.
        /// </summary>
        internal static string OutputXmlSerializer {
            get {
                return ResourceManager.GetString("OutputXmlSerializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contains the XML serialization assemblies for the project. ähnelt.
        /// </summary>
        internal static string OutputXmlSerializerDescription {
            get {
                return ResourceManager.GetString("OutputXmlSerializerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ParameterCannotBeNullOEmpty ähnelt.
        /// </summary>
        internal static string ParameterCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ParameterCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter must be a valid guid. ähnelt.
        /// </summary>
        internal static string ParameterMustBeAValidGuid {
            get {
                return ResourceManager.GetString("ParameterMustBeAValidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter must be a valid item identifier. ähnelt.
        /// </summary>
        internal static string ParameterMustBeAValidItemId {
            get {
                return ResourceManager.GetString("ParameterMustBeAValidItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Item is not available or corrupted and thus cannot be pasted. ähnelt.
        /// </summary>
        internal static string PasteFailed {
            get {
                return ResourceManager.GetString("PasteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The complete path to &apos;{0}&apos; exceeds the maximum number of characters permitted by the file system. ähnelt.
        /// </summary>
        internal static string PathTooLong {
            get {
                return ResourceManager.GetString("PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy if newer ähnelt.
        /// </summary>
        internal static string PreserveNewest {
            get {
                return ResourceManager.GetString("PreserveNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program ähnelt.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project ähnelt.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A reference to library &apos;{0}&apos; cannot be added. Adding this project as a reference would cause a circular dependency.  ähnelt.
        /// </summary>
        internal static string ProjectContainsCircularReferences {
            get {
                return ResourceManager.GetString("ProjectContainsCircularReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project File ähnelt.
        /// </summary>
        internal static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name of the file containing build, configuration, and other information about the project. ähnelt.
        /// </summary>
        internal static string ProjectFileDescription {
            get {
                return ResourceManager.GetString("ProjectFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Folder ähnelt.
        /// </summary>
        internal static string ProjectFolder {
            get {
                return ResourceManager.GetString("ProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The absolute location of the project. ähnelt.
        /// </summary>
        internal static string ProjectFolderDescription {
            get {
                return ResourceManager.GetString("ProjectFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project location is not trusted:{0}{0}{1}{0}{0}Running the application may result in security exceptions when it {0}attempts to perform actions which require full trust.{0}{0}Click OK to ignore and continue. ähnelt.
        /// </summary>
        internal static string ProjectLocationNotTrusted {
            get {
                return ResourceManager.GetString("ProjectLocationNotTrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Properties ähnelt.
        /// </summary>
        internal static string ProjectProperties {
            get {
                return ResourceManager.GetString("ProjectProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project file &apos;{0}&apos; has been modified outside of Visual Studio.  Do you want to reload the project? ähnelt.
        /// </summary>
        internal static string QueryReloadNestedProject {
            get {
                return ResourceManager.GetString("QueryReloadNestedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quiet ähnelt.
        /// </summary>
        internal static string Quiet {
            get {
                return ResourceManager.GetString("Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A reference to component &apos;{0}&apos; cannot be added. A reference to the component already exists in the project. ähnelt.
        /// </summary>
        internal static string ReferenceAlreadyExists {
            get {
                return ResourceManager.GetString("ReferenceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference Properties ähnelt.
        /// </summary>
        internal static string ReferenceProperties {
            get {
                return ResourceManager.GetString("ReferenceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die References ähnelt.
        /// </summary>
        internal static string ReferencesNodeName {
            get {
                return ResourceManager.GetString("ReferencesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Name) ähnelt.
        /// </summary>
        internal static string RefName {
            get {
                return ResourceManager.GetString("RefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display name of the reference ähnelt.
        /// </summary>
        internal static string RefNameDescription {
            get {
                return ResourceManager.GetString("RefNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename directory failed. {0} ähnelt.
        /// </summary>
        internal static string RenameFolder {
            get {
                return ResourceManager.GetString("RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RTL_False ähnelt.
        /// </summary>
        internal static string RTL {
            get {
                return ResourceManager.GetString("RTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save? ähnelt.
        /// </summary>
        internal static string SaveCaption {
            get {
                return ResourceManager.GetString("SaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to save modified documents? ähnelt.
        /// </summary>
        internal static string SaveModifiedDocuments {
            get {
                return ResourceManager.GetString("SaveModifiedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project file can only be saved into the project location &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string SaveOfProjectFileOutsideCurrentDirectory {
            get {
                return ResourceManager.GetString("SaveOfProjectFileOutsideCurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SimpleProjectNode_bmp {
            get {
                object obj = ResourceManager.GetObject("SimpleProjectNode.bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error opening specified view &apos;{0}&apos; using standard editor. ähnelt.
        /// </summary>
        internal static string StandardEditorViewError {
            get {
                return ResourceManager.GetString("StandardEditorViewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - Empty strings ähnelt.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - System reserved names, including &apos;CON&apos;, &apos;AUX&apos;, PRN&apos;, &apos;COM1&apos; or &apos;LPT2&apos; ähnelt.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - contain only &apos;.&apos; ähnelt.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die URL ähnelt.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are trying to use an item that has already been deleted or that does not exist. ähnelt.
        /// </summary>
        internal static string UseOfDeletedItemError {
            get {
                return ResourceManager.GetString("UseOfDeletedItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft .NET Framework v1.0 ähnelt.
        /// </summary>
        internal static string v1 {
            get {
                return ResourceManager.GetString("v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft .NET Framework v1.1 ähnelt.
        /// </summary>
        internal static string v11 {
            get {
                return ResourceManager.GetString("v11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft .NET Framework v2.0 ähnelt.
        /// </summary>
        internal static string v2 {
            get {
                return ResourceManager.GetString("v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft .NET Framework v3.0 ähnelt.
        /// </summary>
        internal static string v3 {
            get {
                return ResourceManager.GetString("v3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft .NET Framework v3.5 ähnelt.
        /// </summary>
        internal static string v35 {
            get {
                return ResourceManager.GetString("v35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft .NET Framework v4.0 ähnelt.
        /// </summary>
        internal static string v4 {
            get {
                return ResourceManager.GetString("v4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die warning ähnelt.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows Application ähnelt.
        /// </summary>
        internal static string WinExe {
            get {
                return ResourceManager.GetString("WinExe", resourceCulture);
            }
        }
    }
}
